### ISSUE TITLE
Create an Interactive Readme.md

### ISSUE THREAD

**Issue by stephin007** [stephin007/WeatherMan#7]
Whomsoever reading this, Fork this repo and run it locally ,for which you have to do the following

git clone <repo_link>
cd into project folder
npm install
npm start
By doing this you will get to know, what does this application do.

Also, please leave a 🌟  if you like the project.

**Comment by Justinnn07** [comment]
@stephin007 sir, i am willing to create an interactive Readme.md , kindly assign it to me😊

**Comment by stephin007** [comment]
@Justinnn07 Please go ahead!

**Comment by stephin007** [comment]
@Justinnn07 Please fork the project and then clone it! then make a separate branch for it and then raise a PR to my master
your branch naming convention must be:
(your username)/editReadme

**Comment by Justinnn07** [comment]
> @Justinnn07 Please fork the project and then clone it! then make a separate branch for it and then raise a PR to my master
> your branch naming convention must be:
> (your username)/editReadme

sure sir!

**Comment by stephin007** [comment]
Any progress yet? @Justinnn07

**Comment by Justinnn07** [comment]
> Any progress yet? @Justinnn07

Will complete by today!
